name: "PR Greeter"
on: [pull_request]

jobs:
  pr-greeter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeter"
        uses: JJ/pr-greeting-action@releases/v0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "Hey **#** welcome to this repo. If you are submitting Pull Request for Hacktoberfest, Then HappyHacking ğŸ±â€ğŸ’»."